# Generated by Django 5.2 on 2025-05-04 06:50

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.CharField(default=myapp.models.generate_short_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('visitor_type', models.CharField(choices=[('employe', 'Employee'), ('contractor', 'Contractor'), ('guest', 'Guest'), ('vendor', 'Vendor')], default='guest', max_length=20)),
                ('identification_type', models.CharField(blank=True, choices=[('nid', 'NID'), ('passport', 'Passport'), ('driving', 'Driving License')], max_length=10, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='localtest/visitor_photos/')),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('track_status', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorEventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=100)),
                ('camera_location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('snapshot_url', models.URLField()),
                ('capture_time', models.DateTimeField()),
                ('detected_time', models.DateTimeField()),
                ('visitor_ids', models.JSONField(default=list)),
                ('institute', models.CharField(blank=True, max_length=255, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=100, null=True)),
                ('video_process_server_id', models.CharField(blank=True, max_length=100, null=True)),
                ('video_process_server_fixed_id', models.CharField(blank=True, max_length=100, null=True)),
                ('video_process_server_ip', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
