# Generated by Django 5.2 on 2025-04-24 07:01

import myapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_visitor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=myapp.storage_backends.MinioMediaStorage(), upload_to='visitor_photos/'),
        ),
    ]
