# Generated by Django 5.2 on 2025-04-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250415_1752'),
    ]

    operations = [
    ]
