# Generated by Django 5.2 on 2025-05-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_visitoreventhistory_visitor_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitoreventhistory',
            name='visitors',
        ),
        migrations.AddField(
            model_name='visitoreventhistory',
            name='visitor_ids',
            field=models.JSONField(default=list),
        ),
    ]
