# Generated by Django 5.2 on 2025-05-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_visitoreventhistory_visitors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitoreventhistory',
            name='visitors',
            field=models.ManyToManyField(related_name='event_histories', to='myapp.visitor'),
        ),
    ]
