# Generated by Django 5.2 on 2025-04-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_visitor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
