# Generated by Django 5.2 on 2025-04-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_visitor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('nid', 'NID'), ('passport', 'Passport'), ('driving', 'Driving License')], max_length=10, null=True),
        ),
    ]
