# Generated by Django 5.2 on 2025-04-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_visitor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_type',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Contractor'), (3, 'Guest'), (4, 'Vendor')], default=3),
        ),
    ]
