# Generated by Django 5.2 on 2025-04-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_visitor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
