# Generated by Django 5.2 on 2025-04-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_visitor_visitor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_type',
        ),
    ]
