# Generated by Django 5.2 on 2025-05-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_visitoreventhistory_capture_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(blank=True, choices=[('employe', 'Employee'), ('contractor', 'Contractor'), ('guest', 'Guest'), ('vendor', 'Vendor')], default='guest', max_length=20, null=True),
        ),
    ]
