# Generated by Django 4.2 on 2025-05-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_visitor_visitor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitoreventhistory',
            name='video_process_server_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
