# Generated by Django 5.2 on 2025-04-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_visitor_visitor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='localtest/visitor_photos/'),
        ),
    ]
