# Generated by Django 4.2 on 2025-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_visitoreventhistory_video_process_server_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
