# Generated by Django 5.2 on 2025-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_visitor_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorEventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=100)),
                ('camera_location', models.CharField(max_length=255)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('snapshot_url', models.URLField()),
                ('capture_time', models.DateTimeField(auto_now_add=True)),
                ('detected_time', models.DateTimeField()),
                ('visitors', models.ManyToManyField(related_name='tracking_logs', to='myapp.visitor')),
            ],
        ),
    ]
