# Generated by Django 5.2 on 2025-04-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_visitoreventhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitoreventhistory',
            name='visitors',
        ),
        migrations.AddField(
            model_name='visitoreventhistory',
            name='visitor_ids',
            field=models.JSONField(default=list),
        ),
    ]
