# Generated by Django 4.2 on 2025-05-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_visitor_is_tracking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='ml_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
