# Generated by Django 4.2 on 2025-05-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_visitor_ml_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=100, unique=True)),
                ('url', models.TextField()),
                ('location_name', models.CharField(max_length=255)),
                ('institute', models.IntegerField()),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('camera_running_status', models.BooleanField(default=False)),
                ('camera_frame_cap_status', models.BooleanField(default=False)),
                ('video_process_server', models.IntegerField(blank=True, null=True)),
                ('camera_type', models.CharField(max_length=50)),
                ('camera_model', models.CharField(blank=True, max_length=255)),
                ('camera_manufacture', models.CharField(blank=True, max_length=255)),
                ('threshold', models.CharField(max_length=10)),
                ('third_party', models.IntegerField(blank=True, null=True)),
                ('video_process_server_info', models.JSONField(blank=True, null=True)),
                ('third_party_info', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
