# Generated by Django 5.2 on 2025-04-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_visitoreventhistory_visitors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitoreventhistory',
            name='camera_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitoreventhistory',
            name='institute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitoreventhistory',
            name='video_process_server_fixed_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitoreventhistory',
            name='video_process_server_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitoreventhistory',
            name='video_process_server_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitoreventhistory',
            name='camera_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
