# Generated by Django 4.2 on 2025-05-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitoreventhistory',
            name='visitors',
        ),
    ]
