# Generated by Django 5.2 on 2025-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_visitoreventhistory_camera_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitoreventhistory',
            name='video_process_server_ip',
            field=models.CharField(blank=True, null=True),
        ),
    ]
