# Generated by Django 5.2 on 2025-04-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_visitoreventhistory_video_process_server_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitoreventhistory',
            name='capture_time',
            field=models.DateTimeField(),
        ),
    ]
