# Generated by Django 5.2 on 2025-04-30 10:31

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_visitoreventhistory_capture_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='uid',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id',
            field=models.CharField(default=myapp.models.generate_short_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
